name: Build

permissions:
  contents: read

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  detect-module-changes:
    uses: ./.github/workflows/detect-changed-modules.yml

  server:
    name: Build Server
    needs: detect_module_changes
    if: needs.detect-module-changes.outputs.server == 'true' || needs.detect-module-changes.outputs.common == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Server
        run: |
          mvn clean install

  desktop_client:
    name: Build Desktop Client
    needs: detect_module_changes
    if: needs.detect-module-changes.outputs.desktop-client == 'true' || needs.detect-module-changes.outputs.common == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Desktop Client
        run: |
          mvn clean install

  ermis_client:
    name: Build Mobile Client
    needs: detect_module_changes
    if: needs.detect-module-changes.outputs.ermis-client == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.7'

      - name: Build Mobile Client
        working-directory: ErmisClient/Mobile/ermis_client
        run: |
          chmod +x build.sh
          ./build.sh
          flutter analyze --no-fatal-infos --no-fatal-warnings

