name: Build

permissions:
  contents: read

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
  paths-ignore:
      - '**/*.md'

jobs:
  detect-changes:
    name: Detect changed modules
    runs-on: ubuntu-latest

    outputs:
      server: ${{ steps.filter.outputs.server }}
      common: ${{ steps.filter.outputs.common }}
      desktop_client: ${{ steps.filter.outputs.desktop_client }}
      ermis_client: ${{ steps.filter.outputs.ermis_client }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Filter paths
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            server:
              - 'Ermis-Server/**'
            common:
              - 'Ermis-Common/**'
            desktop_client:
              - 'Ermis-Client/Desktop/**'
            ermis_client:
              - 'Ermis-Client/Mobile/**'

  server:
    name: Build Server
    needs: detect-changes
    if: needs.detect-changes.outputs.server == 'true' || needs.detect-changes.outputs.common == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Server
        run: |
          mvn clean install

  desktop_client:
    name: Build Desktop Client
    needs: detect-changes
    if: needs.detect-changes.outputs.desktop_client == 'true' || needs.detect-changes.outputs.common == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Desktop Client
        run: |
          mvn clean install

  ermis_client:
    name: Build Mobile Client
    needs: detect-changes
    if: needs.detect-changes.outputs.ermis_client == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.7'

      - name: Build Mobile Client
        working-directory: ErmisClient/Mobile/ermis_client
        run: |
          chmod +x build.sh
          ./build.sh
          flutter analyze

