name: Mobile Client Release (APKs)

permissions:
  contents: write

on:
  release:
    types: [published]

jobs:
  build:
    if: startsWith(github.ref_name, 'client-mobile')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.7'

      - name: Decode Keystore
        run: |
          mkdir -p android/app/
          touch my-release-key.keystore
          echo "$RELEASE_STORE_FILE_ENCODED" | base64 --decode > android/app/my-release-key.keystore
        env:
          RELEASE_STORE_FILE_ENCODED: ${{ secrets.RELEASE_STORE_FILE_ENCODED }}

      - name: Build
        working-directory: ErmisClient/Mobile/ermis_client
        run: |
          chmod +x build.sh
          ./build.sh
          flutter build apk --release
          flutter build apk --release --split-per-abi
        env:
          RELEASE_STORE_FILE: android/app/my-release-key.keystore
          RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
          RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}

      - name: Upload APKs to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ErmisClient/Mobile/ermis_client/build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            ErmisClient/Mobile/ermis_client/build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            ErmisClient/Mobile/ermis_client/build/app/outputs/flutter-apk/app-x86_64-release.apk
            ErmisClient/Mobile/ermis_client/build/app/outputs/flutter-apk/app-release.apk

